print("Awais Haleem")
print("Python ka Chilla")
print(1 + 2)
print(3 * 4)
print(5 - 6)
print(7 / 8)
print(9 ** 10)
print(11 % 12)
print('Hello, world!')
print(True and False)
print(True or False)
print(not True)
print(None)
